=head1 NAME

Inline::Python::ReportLab - PDF Generation using Python's ReportLab

=head1 SYNOPSIS

 use Inline::Python::ReportLab;
 my $canvas = Inline::Python::ReportLab->Canvas('filename.pdf');
 $canvas->drawString(100,100,"Hello World");
 $canvas->showPage();
 $canvas->save();

=head1 DESCRIPTION

L<Inline::Python::ReportLab> is a VERY naive wrapper around Python's popular PDF generation library L<ReportLab|http://www.reportlab.com/>. It uses the magic of L<Inline::Python>, so that must be installed, as must the C<python> interpreter itself, and the Python ReportLab library obviously.

This module should be viewed as a starting point awaiting contributions. See L<Source Repository> to see where to go to help. The author wrote the module as a proof-of-concept, but would like to see it go farther if people are interested in contributing.

=head1 SEE ALSO

=over

=item *

L<Inline::Python>

=item *

L<ReportLab|http://www.reportlab.com/>

=back

=head1 SOURCE REPOSITORY

L<http://github.com/jberger/Inline-Python-ReportLab>

=head1 AUTHOR

Joel Berger, E<lt>joel.a.berger@gmail.comE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2011 by Joel Berger

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
